# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PMD Code Quality Analysis

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  schedule:
    - cron: "18 3 * * 0"

permissions:
  contents: read

env:
  JAVA_VERSION: "17"

jobs:
  pmd-code-scan:
    name: PMD Static Analysis
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile project for analysis
        run: mvn compile

      - name: Run PMD Analysis
        id: pmd
        uses: pmd/pmd-github-action@967a81f8b657c87f7c3e96b62301cb1a48efef29
        with:
          rulesets: "rulesets/java/quickstart.xml"
          sourcePath: "src/main/java"
          analyzeModifiedFilesOnly: false

      - name: Run Maven PMD Plugin
        run: mvn pmd:check
        continue-on-error: true

      - name: Upload PMD SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: Upload PMD reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pmd-reports
          path: |
            target/pmd.xml
            target/site/pmd.html
            pmd-report.sarif
          retention-days: 7
