name: Security and Dependency Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: "0 6 * * 1" # Weekly on Monday at 6 AM

permissions:
  contents: read
  security-events: write
  actions: read

env:
  JAVA_VERSION: "17"

jobs:
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache OWASP Dependency Check database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-owasp-db-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-owasp-db

      - name: Run OWASP Dependency Check
        run: |
          mvn org.owasp:dependency-check-maven:check \
            -DfailBuildOnCVSS=7 \
            -DsuppressionsLocation=owasp-suppressions.xml \
            -Dformats=HTML,XML,SARIF
        continue-on-error: true

      - name: Upload OWASP Dependency Check SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: target/dependency-check-report.sarif

      - name: Upload OWASP reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: owasp-dependency-check-reports
          path: |
            target/dependency-check-report.html
            target/dependency-check-report.xml
            target/dependency-check-report.sarif
          retention-days: 30

  spotbugs-analysis:
    name: SpotBugs Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile project
        run: mvn compile

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:check
        continue-on-error: true

      - name: Upload SpotBugs reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-reports
          path: |
            target/spotbugs.xml
            target/spotbugsXml.xml
            target/site/spotbugs.html
          retention-days: 7

  license-check:
    name: License Compliance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Generate license report
        run: |
          mvn org.codehaus.mojo:license-maven-plugin:add-third-party
          mvn org.codehaus.mojo:license-maven-plugin:download-licenses

      - name: Check for GPL/LGPL licenses
        run: |
          if [ -f "target/generated-sources/license/THIRD-PARTY.txt" ]; then
            echo "Checking for potentially problematic licenses..."
            if grep -i "gpl\|agpl" target/generated-sources/license/THIRD-PARTY.txt; then
              echo "⚠️ Warning: GPL/AGPL licenses found. Review required."
              exit 1
            else
              echo "✅ No problematic licenses detected."
            fi
          fi
        continue-on-error: true

      - name: Upload license reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: license-reports
          path: |
            target/generated-sources/license/
            target/licenses/
          retention-days: 7

  secrets-scan:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

  docker-security-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: rakcha:security-scan
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "rakcha:security-scan"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-security-scan
          path: trivy-results.sarif
          retention-days: 7

  security-summary:
    name: Security Scan Summary
    runs-on: ubuntu-latest
    needs: [dependency-check, spotbugs-analysis, license-check, secrets-scan]
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create security summary
        run: |
          echo "# Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Scan Type | Status | Details |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|---------|" >> $GITHUB_STEP_SUMMARY
          echo "| OWASP Dependency Check | ${{ needs.dependency-check.result }} | Checks for known vulnerabilities in dependencies |" >> $GITHUB_STEP_SUMMARY
          echo "| SpotBugs Analysis | ${{ needs.spotbugs-analysis.result }} | Static analysis for potential bugs and security issues |" >> $GITHUB_STEP_SUMMARY
          echo "| License Compliance | ${{ needs.license-check.result }} | Verifies license compatibility |" >> $GITHUB_STEP_SUMMARY
          echo "| Secret Detection | ${{ needs.secrets-scan.result }} | Scans for exposed secrets in code |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Recommendations" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Review any high-severity vulnerabilities immediately" >> $GITHUB_STEP_SUMMARY
          echo "- Update dependencies regularly" >> $GITHUB_STEP_SUMMARY
          echo "- Monitor for new security advisories" >> $GITHUB_STEP_SUMMARY
          echo "- Ensure no secrets are committed to the repository" >> $GITHUB_STEP_SUMMARY
